version: '3.9'
services:
  readme2.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme2.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INIT_DB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme2.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme2.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme2.user.mongo.ui
    ports:
      - 8081:8081

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme2.account.mongo:${MONGO_PORT}/

volumes:
  readme2.mongo.account:
